[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

  [build.environment]
    IGNORE_ENV_FILE_WARNINGS = "true"
    SECRETS_SCAN_OMIT_PATHS = "dist/assets/index-B-T7gGJm.js"
    SECRETS_SCAN_OMIT_KEYS = "PINTEREST_CLIENT_SECRET"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
